save_flag: true

patchworkpp:
    
    sensor_height: 1.723

    mode: "czm" 
    verbose: false   # To check effect of uprightness/elevation/flatness
    visualize: true # Ground Likelihood Estimation is visualized
    
    # Ground Plane Fitting parameters
    num_iter: 3
    num_lpr: 20
    num_min_pts: 10
    th_seeds: 0.3
    th_dist: 0.125
    th_seeds_v: 0.25
    th_dist_v: 0.1
    max_r: 80.0
    min_r: 2.7 # to consider vicinity of mobile platform.
    uprightness_thr: 0.707 # 45: 0.707 / 60: 0.866

    adaptive_seed_selection_margin: -1.2 # The points below the adaptive_seed_selection_margin * sensor_height are filtered
    uniform: # deprecated
        num_rings: 16
        num_sectors: 54
    czm:
        num_zones: 4
        num_sectors_each_zone: [16, 32, 54, 32]
        mum_rings_each_zone: [2, 4, 4, 4]
        elevation_thresholds:  [0.0, 0.0, 0.0, 0.0] # For elevation. The size should be equal to flatness_thresholds vector
        flatness_thresholds:  [0.0, 0.0, 0.0, 0.0]  # For flatness. The size should be equal to elevation_thresholds vectorc

    flatness_margin: 0.0
    noise_filter_channel_num: 20

    enable_TGR : true
    enable_RNR : true
    pc_num_channel: 2048
    intensity_thr: 0.2